name: Deploy hubang

on:
  # 手动触发
  workflow_dispatch:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    # 使用ubuntu系统镜像运行自动化脚本
    runs-on: ubuntu-latest

    steps:
      # 切换分支
      - uses: actions/checkout@v2

      #      # 下载 git submodule
      #      - uses: srt32/git-actions@v0.0.3
      #        with:
      #          args: git submodule update --init --recursive

      # 使用 node:16
      - name: use Node.js 14.18.1
        id: node
        uses: actions/setup-node@v2
        with:
          node-version: "14.18.1"

      # 缓存 node modules
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # npm install
      - name: Install Dependencies
        if: steps.node.outputs.cache-hit != 'true'
        run: |
          npm -v
          npm install

      # Create .env
      - name: Create .env
        env:
          ACCESSKEY: ${{ secrets.ACCESSKEY }}
          SECRETKEY: ${{ secrets.SECRETKEY }}
        run: |
          echo ACCESSKEY="$ACCESSKEY" >> .env
          echo SECRETKEY="$SECRETKEY" >> .env
        shell: bash

      # build
      - name: Build
        run: npm run publish

      # tar
      - name: Tar dist
        run:|
          ls
          tar zcf build.tar.gz build package.json package-lock.json next.config.js static

          # Deploy to server
      - name: Deploy to server
        id: deploy
        uses: cross-the-world/scp-pipeline@master
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USERNAME }}
          pass: ${{ secrets.SERVER_PASS }}
          connect_timeout: 10s
          local: "build.tar.gz"
          remote: /www/wwwroot/hubang

      # 远程Command
      - name: Command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            cd /www/wwwroot/hubang
            tar zxf build.tar.gz
            rm build.tar.gz
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm i
            pm2 delete hubang
            npm run pm2
            pm2 save
            echo "Complete!!!"
